import * as yup from 'yup'

export const useValidationParticipant = yup
  .object()
  .shape({
    idTipDoc: yup.string(),
    nombre: yup.string(),
    apellido: yup.string(),
    numDoc: yup.string(),
    email: yup.string(),
    fono: yup.string(),
    distrito: yup.string(),
    provincia: yup.string(),
    region: yup.string(),
    edad: yup.string(),
    flagEmprendimiento: yup.boolean(),
    flagAccesoTecno: yup.boolean(),
    fecNacimiento: yup.string(),
    fecVencimiento: yup.string(),
    aniosEmprendimiento: yup.string(),
    flagVentaInternet: yup.boolean(),
    salud_idSexo: yup.string().required('Dato es requerido'),
    salud_idOtrosDependientes: yup.string().required('Dato es requerido'),
    salud_idCondAlojamiento: yup.string().required('Dato es requerido'),
    salud_idRedSoporte: yup.string().required('Dato es requerido'),
    salud_idNivelEducativo: yup.string().required('Dato es requerido'),
    salud_idIngresoProm: yup.string().required('Dato es requerido'),
    salud_idIdentGenero: yup.string().required('Dato es requerido'),
    salud_idOrientacion: yup.string().required('Dato es requerido'),
    salud_idEmbarazo: yup.string().required('Dato es requerido'),
    salud_idHacimiento: yup.string().required('Dato es requerido'),
    salud_idCondMigratoria: yup.string().required('Dato es requerido'),
    salud_idCondLaboral: yup.string().required('Dato es requerido'),
    salud_idEdad: yup.string().required('Dato es requerido'),
    salud_idDependientes: yup.string().required('Dato es requerido'),
    salud_idCondFisica: yup.string().required('Dato es requerido'),
    salud_idSobreviviente: yup.string().required('Dato es requerido'),
    salud_idDocPosee: yup.string().required('Dato es requerido'),
    salud_idSeguroSalud: yup.string().required('Dato es requerido'),
    salud_idNacionalidad: yup.string().required('Dato es requerido'),
    vida_idSexo: yup.string().required('Dato es requerido'),
    vida_idOtrosDependientes: yup.string().required('Dato es requerido'),
    vida_idCondAlojamiento: yup.string().required('Dato es requerido'),
    vida_idRedSoporte: yup.string().required('Dato es requerido'),
    vida_idNivelEducativo: yup.string().required('Dato es requerido'),
    vida_idEdad: yup.string().required('Dato es requerido'),
    vida_idFamDirectos: yup.string().required('Dato es requerido'),
    vida_idOrientacion: yup.string().required('Dato es requerido'),
    vida_idEmbarazo: yup.string().required('Dato es requerido'),
    vida_idHacimiento: yup.string().required('Dato es requerido'),
    vida_idCondMigratoria: yup.string().required('Dato es requerido'),
    vida_idCondLaboral: yup.string().required('Dato es requerido'),
    vida_idNacionalidad: yup.string().required('Dato es requerido'),
    vida_idIdentGenero: yup.string().required('Dato es requerido'),
    vida_idDependientes: yup.string().required('Dato es requerido'),
    vida_idCondFisica: yup.string().required('Dato es requerido'),
    vida_idSobreviviente: yup.string().required('Dato es requerido'),
    vida_idDocPosee: yup.string().required('Dato es requerido'),
    vida_idIngresoProm: yup.string().required('Dato es requerido'),
    vida_idTipoResidencia: yup.string().required('Dato es requerido'),
    vida_idHorasTrabajo: yup.string().required('Dato es requerido')
  })
  .required()
