import { BaseModel } from '../../common/model/base-model'

class MediosVida extends BaseModel {
  idTipoCalculo: string = ''
  idSexo: string = ''
  idOrientacion: string = ''
  idDependientes: string = ''
  idOtrosDependientes: string = ''
  idEmbarazo: string = ''
  idCondFisica: string = ''
  idCondAlojamiento: string = ''
  idHacimiento: string = ''
  idSobreviviente: string = ''
  idRedSoporte: string = ''
  idCondMigratoria: string = ''
  idNivelEducativo: string = ''
  idCondLaboral: string = ''
  idSeguroSalud: string = ''
  idIngresoProm: string = ''
  idEdad: string = ''
  idNacionalidad: string = ''
  idIdentGenero: string = ''
  idTipoResidencia: string = ''
  idHorasTrabajo: string = ''
  idFamDirectos: string = ''
  dscSexo: string = ''
  dscOrientacion: string = ''
  dscDependientes: string = ''
  dscOtrosDependientes: string = ''
  dscEmbarazo: string = ''
  dscCondFisica: string = ''
  dscCondAlojamiento: string = ''
  dscHacimiento: string = ''
  dscSobreviviente: string = ''
  dscRedSoporte: string = ''
  dscCondMigratoria: string = ''
  dscNivelEducativo: string = ''
  dscCondLaboral: string = ''
  dscSeguroSalud: string = ''
  dscIngresoProm: string = ''
  dscEdad: string = ''
  dscNacionalidad: string = ''
  dscIdentGenero: string = ''
  idDocPosee: string = ''
  dscDocPosee: string = ''
}

export { MediosVida }
